package.json
=> Fix: yarn dev command

demo-app/package.json, demo-app/src/components/FormSubmitter.vue, demo-app/tests/unit/FormSubmitter.spec.js, demo-app/yarn.lock, src/simulating-user-input.md
=> Work on trigger guide

demo-app/src/components/SubmitButton.vue, demo-app/tests/unit/SubmitButton.spec.js, src/components-with-props.md, src/ja/components-with-props.md
1. translate props to english
2. improve the japanese section a little
=> Translate props page to English

.eslintrc, demo-app/package.json, demo-app/src/components/ComponentWithGetters.vue, demo-app/src/components/ComponentWithVuex.vue, demo-app/tests/unit/ComponentWithVuex.spec.js, demo-app/yarn.lock, src/.vuepress/config.js, src/testing-vuex.md, src/vuex-in-components-mutations-and-getters.md, src/vuex-in-components.md
=> Add Vuex in components guide

demo-app/jest.config.js, demo-app/jest.init.js, demo-app/src/components/Bilingual.vue, demo-app/src/translations.js, demo-app/tests/unit/Bilingual.spec.js, src/mocking-global-objects.md
=> Add mocks guide

demo-app/src/store/mutations.js, demo-app/tests/unit/mutations.spec.js, src/vuex-mutations.md
Pretty simple stuff.
resolves #31
=> Add mutations guide

src/jest-mocking-modules.md, src/vue-router.md
=> Update outline for incomplete sections

README.md
=> readme-ja-fix

src/vuex-mutations.md
The mutation name should be SET_POST, not SET_USER
=> Fix typo on mutation

src/testing-emitted-events.md
Corrected the description of the test that was in Japanese for English.
=> Correction test description

src/setting-up-for-tdd.md
Small typo fix while reading the doc :)
=> Fix unbalenced parens in Setting up for TDD

src/vue-router.md
* Strategies
* behave
* decoupling
=> docs(vue-router): fixes typos

src/finding-elements-and-components.md
=> Fix broken link

src/ja/simulating-user-input.md, src/simulating-user-input.md
=> Use v-if in simulating user input example

src/vuex-in-components.md
Thank you for the good handbook.
I fixed typo and broken links. Please review it.
=> Fix typo and broken links

src/vuex-getters.md
Some real basic housecleaning stuff, but hopefully it's helpful. Thanks so much for creating this great resource.
=> Vuex getters typo fixes/formatting consistency

demo-app/src/components/ComponentWithButtons.vue, demo-app/tests/unit/ComponentWithButtons.spec.js, src/vuex-in-components-mutations-and-actions.md
=> Add example testing a namespaced module

src/ja/vuex-getters.md
fix https://github.com/lmiller1990/vue-testing-handbook/issues/119
@lmiller1990 
I transrated this file to the Japanese. Please check it in your free time 😀
=> Translate vuex-getters to Japanese.

src/vue-router.md
=> Update vue-router's beforeRouteLeave

src/components-with-props.md
i fixed mistake spelling in `components-with-props.md`, please check it :+1:
=> fix word mistake spelling

src/components-with-props.md
the descriptions did not match the tests
=> swap descriptions

src/testing-vuex.md
After reading the documentation on testing Vuex, the last sentence seemed a bit confusing. It seems to me as if the guides first talk about testing Vuex in isolation and then components that use the Vuex store? I have changed the sentence to account for that.
=> Updates documentation for testing vuex

src/vuex-in-components-mutations-and-actions.md, src/vuex-in-components.md
Not sure if it was supposed to say "a new store" or "the new store".
=> fix minor typo
